### ISSUE TITLE
güvenlik

### ISSUE THREAD

**Issue by bababoyy** [BlueClimpy/Blueizm-Bot#2]
botun tokeni ana java dosyasında gözüküyor

**Comment by efehalilbeyoglu** [comment]
Merhaba! 

Haber ettiğin için teşekkürler fakat o botu çoktan silmiştim ancak yine de az bir ihtimalde olsa o token kullanılıyor olma ihtimaline karşın kaldıracağım o kısmı. İyi akşamlar:)
